# Generated by Django 3.1.3 on 2020-11-18 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='additional_information',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
