# Generated by Django 3.1.3 on 2020-11-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='Corey_MS_default.jpg', null=True, upload_to='product_pics'),
        ),
    ]
