# Generated by Django 3.1.3 on 2020-11-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20201125_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='default-product.jpg', null=True, upload_to='product_images'),
        ),
    ]
