# Generated by Django 3.1.3 on 2020-12-10 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='number',
        ),
    ]
