# Generated by Django 3.1.3 on 2020-12-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_auto_20201210_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default=False, null=True, upload_to='product_images'),
        ),
    ]
