# Generated by Django 3.1.3 on 2020-12-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_auto_20201211_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_subs1',
            field=models.ImageField(blank=True, null=True, upload_to='product_images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_subs2',
            field=models.ImageField(blank=True, null=True, upload_to='product_images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_subs3',
            field=models.ImageField(blank=True, null=True, upload_to='product_images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_subs4',
            field=models.ImageField(blank=True, null=True, upload_to='product_images'),
        ),
    ]
