# Generated by Django 3.1.3 on 2020-12-14 19:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_auto_20201214_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_order',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 14, 19, 11, 3, 782246, tzinfo=utc)),
        ),
    ]
